### ISSUE TITLE
Handling releases

### ISSUE THREAD

**Issue by control-toolbox** [control-toolbox/control-toolbox.github.io#10]
Voir comment on gère les releases. Par exemple, j'ai dans le registre `ct`, les versions 0.1.0 et 0.1.1 de `CommonSolveOptimisation` mais sur le dépôt `github` il n'y a que la version 0.1.1. Faut-il faire un tag ? Et pour la doc ?

**Comment by ocots** [comment]
Un début d'explication [ici](https://github.com/control-toolbox/control-toolbox.github.io/wiki/Make-a-release).
