### ISSUE TITLE
Solver arguments

### ISSUE THREAD

**Issue by ocots** [control-toolbox/control-toolbox.github.io#11]
Continuer à utiliser la notion de descriptions dans les appels aux solveurs pour le choix des méthodes mais par la suite, ajouter un appel à la `SciML` avec en argument une donnée de type  `Algorithme` qui définit la méthode. Pour le moment, d'après cette [page](https://docs.sciml.ai/NonlinearSolve/stable/solvers/NonlinearSystemSolvers/#Full-List-of-Methods) l'utilisation d'une fonction qui est évaluée permet de choisir le wrapper/méthode qui va être appelée. Pour choisir la sous-méthode, c'est par passage de `Symbol`, c-a-d quelque chose dans l'esprit de ma description. 

Le fait de passer une donnée de type `Algorithme` permet d'utiliser le multiple dispatch. A voir à quel point on créer son propre sous-type d'algorithme pour faire sa propre méthode. Voir par exemple cette [page](https://docs.sciml.ai/NonlinearSolve/stable/tutorials/nonlinear/).

**Comment by control-toolbox** [comment]
Je propose finalement de remplacer la notion de description par un passage d'algorithme. L'algorithme en revanche peut prendre en argument une description et des options. Ainsi, les options ne sont pas passées au solveur mais à l'algorithme. Ceci a du sens car on peut utiliser des algos variés et donc les options dépendent de ce choix. 

Une question reste à trancher. Par exemple si on veut faire du tir. Est-ce que l'on importe le package `NonlinearSolve` avec un `using` ou faisons-nous un `@reexport` dans `OptimalControl.jl` pour n'avoir qu'un seul `using`.

**Comment by ocots** [comment]
Je propose finalement de remplacer la notion de description par un passage d'algorithme. L'algorithme en revanche peut prendre en argument une description et des options. Ainsi, les options ne sont pas passées au solveur mais à l'algorithme. Ceci a du sens car on peut utiliser des algos variés et donc les options dépendent de ce choix. 

Une question reste à trancher. Par exemple si on veut faire du tir. Est-ce que l'on importe le package `NonlinearSolve` avec un `using` ou faisons-nous un `@reexport` dans `OptimalControl.jl` pour n'avoir qu'un seul `using`.

**Comment by ocots** [comment]
On définit un type abstrait `ControlToolboxAlgorithm` par exemple et des fonctions dessus qui lèvent une exception pour ensuite redéfinir via le multiple dispatch ces mêmes fonctions si un type concret.

**Comment by ocots** [comment]
On pourrait utiliser les deux : soit une description, soit un algorithme.

**Comment by ocots** [comment]
C'est en cours de création...
