### ISSUE TITLE
Todo / Roadmap for the control-toolbox eco-system

### ISSUE THREAD

**Issue by ocots** [control-toolbox/control-toolbox.github.io#12]
## General

- [Description vs Algorithm](https://github.com/control-toolbox/control-toolbox.github.io/issues/11)

## OptimalControl

- [Formulation of the ocp](https://github.com/control-toolbox/OptimalControl.jl/issues/30)
- [Direct shooting](https://github.com/control-toolbox/OptimalControl.jl/issues/28)
- [Indirect shooting](https://github.com/control-toolbox/OptimalControl.jl/issues/24) and [path following](https://github.com/control-toolbox/control-toolbox.github.io/issues/5)
- [Step by step and callback by iteration](https://github.com/control-toolbox/OptimalControl.jl/issues/22)
- interface to JuMP, new OCP type...

## Flows

- [StaticArrays and benchmark](https://github.com/control-toolbox/HamiltonianFlows.jl/issues/7)

## CommonSolveEquations

- [Bridge to NonLinearSolver and Description vs Method](https://github.com/control-toolbox/CommonSolveEquations.jl/issues/2). See also [Symbols rather than enumeration for options](https://github.com/control-toolbox/OptimalControl.jl/issues/52)

## Documentation

- [Modules, docstrings, examples](https://github.com/control-toolbox/control-toolbox.github.io/issues/4)

**Comment by ocots** [comment]
![flow](https://user-images.githubusercontent.com/66357348/215073792-7a2a69e1-e674-48c3-bb11-099fbd35733d.jpeg)

**Comment by ocots** [comment]
A vérifier que le type `Solution` ne dépend que du type `Problem` dans `SciML`. A voir nous comment on veut gérer cela. Le type `Solution` pourrait dépendre de la paire `Problem-Algorithm` ou que de `Problem`. Par contre, du point de vue utilisateur, c'est invisible car on aura les mêmes appels, par exemple `plot(solution)`.

**Comment by ocots** [comment]
Il faudrait bien définir les différents algorithmes qui nous intéressent : Direct Collocation, Shooting...

**Comment by ocots** [comment]
2023-02-06 Snapshot 

## General

* [Description vs Algorithm](https://github.com/control-toolbox/control-toolbox.github.io/issues/11)

## OptimalControl.jl

* [Formulation of the OCP](https://github.com/control-toolbox/OptimalControl.jl/issues/30)
* [Direct shooting](https://github.com/control-toolbox/OptimalControl.jl/issues/28)
* [Indirect shooting](https://github.com/control-toolbox/OptimalControl.jl/issues/24)

**Comment by jbcaillau** [comment]
👍🏽 @ocots

à l’occasion, testons aussi les [discussions](https://github.com/control-toolbox/OptimalControl.jl/discussions/79) ; discord / slack TB par ailleurs, mais
- pouvoir transformer une discussion en issue est pratique
- on a plusieurs fois eu le cas de chats discords qu’on a finalement trouvé utile de recopier dans une issue

**Comment by ocots** [comment]
C'est vrai que c'est plus une discussion qu'une issue.

**Comment by ocots** [comment]
On passe aux discussions. La discussion courante se trouve [ici](https://github.com/control-toolbox/OptimalControl.jl/discussions/88).
