### ISSUE TITLE
Math rendering on .io page

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/control-toolbox.github.io#30]
@ocots No proper rendering by default, see [this post](https://github.com/orgs/community/discussions/22525)

**Comment by ocots** [comment]
I think I will move the OCP math def into the doc of `OptimalControl.jl` but thanks for this.

**Comment by ocots** [comment]
On peut utiliser `Jekyll` pour le site, c'est assez simple. Il suffit d'ajouter un fichier `_config.yml` et puis c'est tout. Ensuite, il y a pleins d'options : https://jekyllrb.com/docs/

**Comment by jbcaillau** [comment]
yes. jekyll is the recommended thing for this (see previous post). but moving math stuff to the main repo is fine too, just leaving general / institutional text info on the web page of the organisation.

**Comment by ocots** [comment]
I have started the page: https://control-toolbox.github.io

You can modify. I am not sure for "Partners".

**Comment by jbcaillau** [comment]
it is fine like this, with the update cnrs logo ✅
