### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by control-toolbox** [control-toolbox/control-toolbox.github.io#4]
Commencer les documentations :
* ajouter les docstrings dans les sources
* ajouter des exemples à partir des exemples dans les répertoires `examples`

**Comment by control-toolbox** [comment]
Voir si on découpe les packages en modules pour simplifier la génération de la documentation.

**Comment by control-toolbox** [comment]
A voir comment générer les exemples : à partir de fichiers markdown ou julia ?

**Comment by ocots** [comment]
A voir : https://fredrikekre.github.io/Literate.jl/v2/fileformat/ 
[https://discourse.julialang.org/t/documenter-from-notebook-to-markdown-with-docstrings/24657/9](https://discourse.julialang.org/t/documenter-from-notebook-to-markdown-with-docstrings/24657/9)
